// Card definitions — pure data, no logic.
// Distribution per deck: 7 attack, 6 effect, 3 relawan, 2 skandal, 1 media, 1 foulplay

export const CARD_TYPES = {
  ATTACK: 'attack',
  EFFECT: 'effect',
  RELAWAN: 'relawan',
  SKANDAL: 'skandal',
  MEDIA: 'media',
  FOULPLAY: 'foulplay',
};

export const ASPECTS = ['Ekonomi', 'Kesehatan', 'Keamanan', 'Pendidikan', 'Infrastruktur'];

// Base deck template — 20 cards, max 2 copies of any non-foulplay card, max 1 foulplay
export const BASE_DECK = [
  // ── ATTACK (7) ──────────────────────────────────────────────────────────────
  {
    id: 'kampanye_ekonomi',
    name: 'Kampanye Ekonomi',
    type: 'attack',
    color: 'red',
    description: 'Ekonomi kamu +12',
    effects: [
      {
        id: 'kampanye_ekonomi_eff',
        type: 'growth',
        target: 'Ekonomi',
        targetPlayer: 'self',
        delta: 12,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Kampanye Ekonomi',
      },
    ],
  },
  {
    id: 'kampanye_ekonomi',
    name: 'Kampanye Ekonomi',
    type: 'attack',
    color: 'red',
    description: 'Ekonomi kamu +12',
    effects: [
      {
        id: 'kampanye_ekonomi_eff',
        type: 'growth',
        target: 'Ekonomi',
        targetPlayer: 'self',
        delta: 12,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Kampanye Ekonomi',
      },
    ],
  },
  {
    id: 'serangan_kesehatan',
    name: 'Krisis Fasilitas',
    type: 'attack',
    color: 'red',
    description: 'Kesehatan lawan −15',
    effects: [
      {
        id: 'serangan_kesehatan_eff',
        type: 'decay',
        target: 'Kesehatan',
        targetPlayer: 'opponent',
        delta: -15,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Krisis Fasilitas',
      },
    ],
  },
  {
    id: 'serangan_kesehatan',
    name: 'Krisis Fasilitas',
    type: 'attack',
    color: 'red',
    description: 'Kesehatan lawan −15',
    effects: [
      {
        id: 'serangan_kesehatan_eff',
        type: 'decay',
        target: 'Kesehatan',
        targetPlayer: 'opponent',
        delta: -15,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Krisis Fasilitas',
      },
    ],
  },
  {
    id: 'kampanye_keamanan',
    name: 'Patroli Nasional',
    type: 'attack',
    color: 'blue',
    description: 'Keamanan kamu +10',
    effects: [
      {
        id: 'kampanye_keamanan_eff',
        type: 'growth',
        target: 'Keamanan',
        targetPlayer: 'self',
        delta: 10,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Patroli Nasional',
      },
    ],
  },
  {
    id: 'serangan_pendidikan',
    name: 'Anggaran Dipangkas',
    type: 'attack',
    color: 'red',
    description: 'Pendidikan lawan −12',
    effects: [
      {
        id: 'serangan_pendidikan_eff',
        type: 'decay',
        target: 'Pendidikan',
        targetPlayer: 'opponent',
        delta: -12,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Anggaran Dipangkas',
      },
    ],
  },
  {
    id: 'serangan_infrastruktur',
    name: 'Proyek Mangkrak',
    type: 'attack',
    color: 'red',
    description: 'Infrastruktur lawan −10, Infrastruktur kamu +5',
    effects: [
      {
        id: 'proyek_mangkrak_opp',
        type: 'decay',
        target: 'Infrastruktur',
        targetPlayer: 'opponent',
        delta: -10,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Proyek Mangkrak',
      },
      {
        id: 'proyek_mangkrak_self',
        type: 'growth',
        target: 'Infrastruktur',
        targetPlayer: 'self',
        delta: 5,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Proyek Mangkrak',
      },
    ],
  },

  // ── EFFECT (6) ──────────────────────────────────────────────────────────────
  {
    id: 'koalisi_partai',
    name: 'Koalisi Partai',
    type: 'effect',
    color: 'blue',
    description: 'Semua aspek +3/giliran selama 5 giliran',
    effects: [
      {
        id: 'koalisi_aura',
        type: 'aura',
        target: 'all',
        targetPlayer: 'self',
        delta: 3,
        deltaType: 'flat',
        durationTurns: 5,
        triggerOn: 'tick',
        condition: null,
        exclusive: false,
        sourceCard: 'Koalisi Partai',
      },
    ],
  },
  {
    id: 'koalisi_partai',
    name: 'Koalisi Partai',
    type: 'effect',
    color: 'blue',
    description: 'Semua aspek +3/giliran selama 5 giliran',
    effects: [
      {
        id: 'koalisi_aura',
        type: 'aura',
        target: 'all',
        targetPlayer: 'self',
        delta: 3,
        deltaType: 'flat',
        durationTurns: 5,
        triggerOn: 'tick',
        condition: null,
        exclusive: false,
        sourceCard: 'Koalisi Partai',
      },
    ],
  },
  {
    id: 'penurunan_ekonomi',
    name: 'Penurunan Ekonomi',
    type: 'effect',
    color: 'red',
    description: 'Ekonomi lawan −5/giliran selama 4 giliran',
    effects: [
      {
        id: 'penurunan_ekonomi_decay',
        type: 'decay',
        target: 'Ekonomi',
        targetPlayer: 'opponent',
        delta: -5,
        deltaType: 'flat',
        durationTurns: 4,
        triggerOn: 'tick',
        condition: null,
        exclusive: false,
        sourceCard: 'Penurunan Ekonomi',
      },
    ],
  },
  {
    id: 'viral_medsos',
    name: 'Viral Media Sosial',
    type: 'effect',
    color: 'blue',
    description: 'Kartu berikutnya yang dimainkan +50% efek (sekali pakai)',
    effects: [
      {
        id: 'viral_amplify',
        type: 'amplify',
        target: 'all',
        targetPlayer: 'self',
        delta: 50,
        deltaType: 'percent',
        durationTurns: -1,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: true,
        sourceCard: 'Viral Media Sosial',
      },
    ],
  },
  {
    id: 'bocoran_data',
    name: 'Bocoran Data',
    type: 'effect',
    color: 'blue',
    description: 'Lihat 1 kartu lawan selama 2 giliran',
    effects: [
      {
        id: 'bocoran_reveal',
        type: 'reveal',
        target: 'opponent',
        targetPlayer: 'opponent',
        delta: 0,
        deltaType: 'flat',
        durationTurns: 2,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Bocoran Data',
      },
    ],
  },
  {
    id: 'lock_kebijakan',
    name: 'Kebijakan Diblokir',
    type: 'effect',
    color: 'red',
    description: 'Lawan tidak bisa memainkan kartu Attack selama 2 giliran',
    effects: [
      {
        id: 'lock_attack',
        type: 'lock',
        target: 'attack',
        targetPlayer: 'opponent',
        delta: 0,
        deltaType: 'flat',
        durationTurns: 2,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: true,
        sourceCard: 'Kebijakan Diblokir',
      },
    ],
  },

  // ── RELAWAN (3) ─────────────────────────────────────────────────────────────
  {
    id: 'relawan_desa',
    name: 'Relawan Desa',
    type: 'relawan',
    color: 'blue',
    description: 'Kesehatan +8, Pendidikan +8',
    effects: [
      {
        id: 'relawan_desa_kes',
        type: 'growth',
        target: 'Kesehatan',
        targetPlayer: 'self',
        delta: 8,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Relawan Desa',
      },
      {
        id: 'relawan_desa_pend',
        type: 'growth',
        target: 'Pendidikan',
        targetPlayer: 'self',
        delta: 8,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Relawan Desa',
      },
    ],
  },
  {
    id: 'konsentrasi',
    name: 'Konsentrasi Kampanye',
    type: 'relawan',
    color: 'blue',
    description: 'Tarik 2 kartu tambahan',
    effects: [
      {
        id: 'konsentrasi_draw',
        type: 'draw',
        target: 'self',
        targetPlayer: 'self',
        delta: 2,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Konsentrasi Kampanye',
      },
    ],
  },
  {
    id: 'mobilisasi_massa',
    name: 'Mobilisasi Massa',
    type: 'relawan',
    color: 'blue',
    description: 'Infrastruktur +10, Keamanan +6',
    effects: [
      {
        id: 'mobilisasi_infra',
        type: 'growth',
        target: 'Infrastruktur',
        targetPlayer: 'self',
        delta: 10,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Mobilisasi Massa',
      },
      {
        id: 'mobilisasi_keamanan',
        type: 'growth',
        target: 'Keamanan',
        targetPlayer: 'self',
        delta: 6,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Mobilisasi Massa',
      },
    ],
  },

  // ── SKANDAL (2) ─────────────────────────────────────────────────────────────
  {
    id: 'skandal_bpjs',
    name: 'Skandal BPJS',
    type: 'skandal',
    color: 'red',
    description: 'Kesehatan lawan −20, tapi Kesehatan kamu −5',
    effects: [
      {
        id: 'skandal_bpjs_opp',
        type: 'decay',
        target: 'Kesehatan',
        targetPlayer: 'opponent',
        delta: -20,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Skandal BPJS',
      },
      {
        id: 'skandal_bpjs_self',
        type: 'decay',
        target: 'Kesehatan',
        targetPlayer: 'self',
        delta: -5,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Skandal BPJS',
      },
    ],
  },
  {
    id: 'korupsi_proyek',
    name: 'Korupsi Proyek Infrastruktur',
    type: 'skandal',
    color: 'red',
    description: 'Infrastruktur lawan −18, Ekonomi lawan −8',
    effects: [
      {
        id: 'korupsi_infra',
        type: 'decay',
        target: 'Infrastruktur',
        targetPlayer: 'opponent',
        delta: -18,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Korupsi Proyek Infrastruktur',
      },
      {
        id: 'korupsi_ekon',
        type: 'decay',
        target: 'Ekonomi',
        targetPlayer: 'opponent',
        delta: -8,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Korupsi Proyek Infrastruktur',
      },
    ],
  },

  // ── MEDIA (1) ────────────────────────────────────────────────────────────────
  {
    id: 'konferensi_pers',
    name: 'Konferensi Pers',
    type: 'media',
    color: 'blue',
    description: 'Bersihkan semua efek negatif pada kamu; semua aspek +5',
    effects: [
      {
        id: 'konpres_cleanse',
        type: 'cleanse',
        target: 'negative',
        targetPlayer: 'self',
        delta: 0,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Konferensi Pers',
      },
      {
        id: 'konpres_boost',
        type: 'growth',
        target: 'all',
        targetPlayer: 'self',
        delta: 5,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Konferensi Pers',
      },
    ],
  },

  // ── FOUL PLAY (1) ────────────────────────────────────────────────────────────
  {
    id: 'manipulasi_data',
    name: 'Manipulasi Data Pemilu',
    type: 'foulplay',
    color: 'red',
    description: 'Semua aspek lawan −10; suppress Ekonomi lawan 2 giliran',
    effects: [
      {
        id: 'manipulasi_blast',
        type: 'decay',
        target: 'all',
        targetPlayer: 'opponent',
        delta: -10,
        deltaType: 'flat',
        durationTurns: 0,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Manipulasi Data Pemilu',
      },
      {
        id: 'manipulasi_suppress',
        type: 'suppress',
        target: 'Ekonomi',
        targetPlayer: 'opponent',
        delta: 0,
        deltaType: 'flat',
        durationTurns: 2,
        triggerOn: 'onPlay',
        condition: null,
        exclusive: false,
        sourceCard: 'Manipulasi Data Pemilu',
      },
    ],
  },
];

export function createDeck() {
  return BASE_DECK.map((card, index) => ({ ...card, instanceId: `${card.id}_${index}` }));
}
